### ISSUE TITLE
myapp.py - consumer key and secret key is not used anywhere

### ISSUE THREAD

**Issue by ghost** [upwork/python-upwork-oauth2#10]
Kindly note that the consumer_key and consumer_secret variables from the myapp.py in the examples folder are currently assigned values from user input ; however, these values are not utilized in the config dictionary that is passed to the upwork.Config constructor.
I mean, those variables are not used anywhere other than taking input from the user.

```
  consumer_key = input("Please enter consumer key: > ")
  consumer_secret = input("Please enter key secret: > ")
  config = upwork.Config(
        {
            "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "client_secret": "xxxxxxxxxxxxx",
            "redirect_uri": "https://a.callback.url",
        }
    )
```

**Comment by mnovozhylov** [comment]
Hi
It's only an example how it could be specified.
