### ISSUE TITLE
Graphql leading to validation error

### ISSUE THREAD

**Issue by usman-dataprism** [upwork/python-upwork-oauth2#6]
The example query in the myapp.py for graphql does not seem to be working as expected. Upon running the query:

```
query = """
            query {
                user {
                id
                nid
                rid
                }
                
            }"""
pprint(graphql.Api(client).execute({'query': query}))
```

I am getting the following error:

```
{'errors': [{'extensions': {'classification': 'ValidationError'},
             'locations': [{'column': 17, 'line': 3}],
             'message': "Validation error of type FieldUndefined: Field 'user' "
                        "in type 'Query' is undefined @ 'user'"}]}
```
                        
Is this funtional?

Thanks,
Usman

**Comment by mnovozhylov** [comment]
Hi @usman-dataprism ,
It's functional, but at the moment not available to regular users. Sorry for confusing.

Please, reach out to our Support Team if you have further questions.
