### ISSUE TITLE
Rest API sunset

### ISSUE THREAD

**Issue by eliyaba** [upwork/python-upwork-oauth2#8]
Hello, 

I see REST API will be sunset soon. Will the existing routers still work? (e.g upwork.routers.workdiary, upwork.routers.auth, upwork.routers.organization.companies)
Should all clients change their code to use upwork.routers.graphql implicitly?

Thank you.

**Comment by mnovozhylov** [comment]
Hi!
Yes, you need to switch to GraphQL.
For further questions related to the migration, please, contact the [Support Team](https://support.upwork.com/).

**Comment by Kick28** [comment]
@mnovozhylov Hi! I have the same question: do I need to tweak some parameters and arguments in your library to use graphQL (as I have seen, there is GraphQL support) or should I use another library? Also, I saw that in the new GraphQL API, there is a lack of features that were widely used in REST. For example, searching through jobs as stated here: https://community.upwork.com/t5/Support-Forum/Is-there-a-way-to-search-through-job-postings-with-new-GraphQL/m-p/1381918
Do you have any updates or recommendations regarding this point?
Thanks in advance!

@eliyaba Did you find the potential solution or maybe some kind of guide for migration?
