### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by Kick28** [upwork/python-upwork-oauth2#9]
@mnovozhylov 
Hi! I commented 3 weeks ago on issue #8 regarding REST API Sunset.
The question is will this package support new GraphQL methods? Because it's more convenient to use the package instead of writing anything by yourself.
The second reason is that I have some problems with running vanilla GraphQL queries. For example, when running jobPosting, I got the next error:  `"message": "'openingsV2DS',  'getOpening',  'Opening not found for uid='~some_string''"`.
How the jobPostingID should look like? My guess that it must be something like this `~some_string`, but maybe I am wrong, because there is nothing described in the documentation yet.
Also, do you plan to release functionality to duplicate REST search for jobs endpoint (https://developers.upwork.com/?lang=python#jobs_search-for-jobs)?
Thank you in advance!

**Comment by mnovozhylov** [comment]
Hi @Kick28 ,
1. The library already supports GraphQL requests. See the example - https://github.com/upwork/python-upwork-oauth2/blob/master/example/myapp.py#L74-L86
2. The questions, not related to the library, should be addressed to [Support Team](https://support.upwork.com)

**Comment by Kick28** [comment]
My bad, didn't check everything well. Thank you for the answer.
